name: JSBridge Node.js Package Version

on:
  release:
    types:
    - prereleased

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set package version
      run: |
        git config user.email "mobilecrm@resco.net"
        git config user.name "resconet"
        npm version ${GITHUB_REF} -m "Set package version to %s"
        git push
